name: surgery
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgomp=15.1.0=h767d61c_5
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.4=h0c1763c_0
  - libuuid=2.41.1=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.2=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.12.11=h9e4cc4f_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - accelerate==1.0.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==3.1.0
      - debugpy==1.8.16
      - decorator==5.2.1
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - executing==2.2.1
      - fastapi==0.116.1
      - ffmpy==0.6.1
      - filelock==3.13.1
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==4.44.0
      - gradio-client==1.3.0
      - h11==0.16.0
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-resources==6.5.2
      - ipykernel==6.28.0
      - ipython==8.20.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - jiter==0.10.0
      - joblib==1.5.2
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - openai==1.56.1
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - peft==0.17.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.4.0
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.1.0
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - ruff==0.12.12
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.37.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.47.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - tomlkit==0.12.0
      - torch==2.5.1+cu118
      - torchaudio==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.46.1
      - triton==3.1.0
      - trl==0.12.0
      - typer==0.17.4
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - wandb==0.17.3
      - wcwidth==0.2.13
      - websockets==12.0
      - xxhash==3.5.0
      - yarl==1.20.1
